// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8IEKMv0yHALdWw6k8I5eyamyr5JfEY',
    appId: '1:981749862755:web:3c00593dbc57c4270ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    authDomain: 'skilloom.firebaseapp.com',
    storageBucket: 'skilloom.appspot.com',
    measurementId: 'G-CSKWQERDN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJBJl9BTH-sqQfkYXTwvKbkzx-OOc-uw',
    appId: '1:981749862755:android:f52b46b8fc982c560ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyEMAYFOKTPHYMOm1exr8afJj3NZu_tU',
    appId: '1:981749862755:ios:0b1f2aec1fb193b50ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
    iosBundleId: 'com.example.skilloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyEMAYFOKTPHYMOm1exr8afJj3NZu_tU',
    appId: '1:981749862755:ios:0b1f2aec1fb193b50ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
    iosBundleId: 'com.example.skilloom',
  );
}
